[package]
name = "transcriptome_module"
version = "0.1.0"
edition = "2021"

[dependencies]
cell_dt_core = { path = "../../cell_dt_core" }
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
rand.workspace = true
